spring:
  profiles: docker
  application.name: ${springboot.app.name:ms-vehicle}
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/uber_vehicle?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: root

server:
  port: 8181
  ribbon:
    eureka.enabled: true
    ServerListRefreshInterval: 1000

eureka:
  client:
    serviceUrl.defaultZone: http://mseurekaserver:8761/eureka/
    registerWithEureka: true
    fetchRegistry: false
    healthcheck.enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 5

management.security.enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc. 
