spring:
  application.name: ${springboot.app.name:ms-payment}
  profiles: docker
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/uber_payment
    username: root
    password: root

server:
  port: 6161
  ribbon:
    eureka.enabled: true
    ServerListRefreshInterval: 1000

eureka:
  client:
    serviceUrl.defaultZone: http://mseurekaserver:8761/eureka/
    registerWithEureka: true
    fetchRegistry: false
    healthcheck.enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 5

#disable the spring security on the management endpoints like /env, /refresh etc.
management.security.enabled: false
