spring.profiles: dev

spring:
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/uber_payment_server?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
  username: root
  password: root

server:
  port: 9090